#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
otp=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi
if [[ $1 == "--otp" ]]; then
	otp=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $otp -eq 1 ]]; then
	pass otp -c "$password" 2>/dev/null
elif [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
